spring:
  application:
    name: AccountService

  datasource:
    url: jdbc:postgresql://${ACCOUNT_DB_HOST:localhost}:${ACCOUNT_DB_PORT:5432}/shopping_db
    username: ${ACCOUNT_DB_USER:user}
    password: ${ACCOUNT_DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # This helps Hibernate translate camelCase Java fields to snake_case DB columns
        physical_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Kafka Configuration (for potential future use)
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:9092

server:
  port: 8081